"""Patch: replaces _pad_rows_with_dummies with centered L/R version."""
import pathlib, ast

path = pathlib.Path("ai_agent/ai_chat_bot/nodes.py")
text = path.read_text(encoding="utf-8")

start_idx = 27260
end_idx   = 31468

new_block = (
    "# -- Row normalisation + dummy padding (centered) "
    "-------------------------------\n"
    "_DUMMY_PITCH = 0.294  # um -- standard finger pitch\n"
    "\n"
    "\n"
    "def _pad_rows_with_dummies(nodes: list) -> list:\n"
    "    \"\"\"\n"
    "    Pad active rows for a perfectly rectangular layout.\n"
    "\n"
    "    Steps (run AFTER matching):\n"
    "      1. SEPARATE   - Drop pre-existing dummies; regenerate fresh.\n"
    "      2. LEFT-ALIGN - Shift each active row so leftmost device is x=0.\n"
    "      3. MEASURE    - Find global max width from ACTIVE rows only.\n"
    "      4. CENTER     - Split dummies evenly L/R around centered transistors.\n"
    "      5. RETURN     - Active nodes (updated x) + new dummy nodes.\n"
    "    \"\"\"\n"
    "    from collections import defaultdict\n"
    "\n"
    "    if not nodes:\n"
    "        return nodes\n"
    "\n"
    "    # Step 1: drop pre-existing dummies, rebuild fresh\n"
    "    active_nodes = [n for n in nodes if not n.get(\"is_dummy\")]\n"
    "    if not active_nodes:\n"
    "        return nodes\n"
    "\n"
    "    # Step 2: group active nodes by row (rounded y)\n"
    "    row_map: dict = defaultdict(list)\n"
    "    for n in active_nodes:\n"
    "        geo = n.get(\"geometry\")\n"
    "        if not geo:\n"
    "            continue\n"
    "        ry = round(float(geo.get(\"y\", 0.0)), 4)\n"
    "        row_map[ry].append(n)\n"
    "\n"
    "    if not row_map:\n"
    "        return nodes\n"
    "\n"
    "    # Step 3: left-align every row to x=0\n"
    "    for ry, rnodes in row_map.items():\n"
    "        leftmost_x = min(float(n[\"geometry\"][\"x\"]) for n in rnodes)\n"
    "        if abs(leftmost_x) > 1e-6:\n"
    "            for n in rnodes:\n"
    "                n[\"geometry\"][\"x\"] = round(float(n[\"geometry\"][\"x\"]) - leftmost_x, 6)\n"
    "            print(f\"[LAYOUT]  y={ry:>7.3f}: shifted left {leftmost_x:.3f}um\", flush=True)\n"
    "\n"
    "    # Step 4: measure global max width from ACTIVE rows only\n"
    "    global_max_right = 0.0\n"
    "    for ry, rnodes in row_map.items():\n"
    "        rightmost = max(rnodes, key=lambda n: float(n[\"geometry\"][\"x\"]))\n"
    "        row_right = float(rightmost[\"geometry\"][\"x\"]) + _DUMMY_PITCH\n"
    "        global_max_right = max(global_max_right, row_right)\n"
    "\n"
    "    if global_max_right <= 0:\n"
    "        return active_nodes\n"
    "\n"
    "    # Snap to integer number of slots\n"
    "    n_slots = round(global_max_right / _DUMMY_PITCH)\n"
    "    global_max_right = n_slots * _DUMMY_PITCH\n"
    "\n"
    "    print(f\"[LAYOUT]  Global width = {global_max_right:.3f}um ({n_slots} slots)\", flush=True)\n"
    "\n"
    "    # Step 5: center each row with equal L/R dummy padding\n"
    "    dummy_counter = 0\n"
    "    new_dummies = []\n"
    "\n"
    "    for ry, rnodes in sorted(row_map.items()):\n"
    "        row_type     = str(rnodes[0].get(\"type\", \"nmos\")).lower()\n"
    "        dummy_type   = \"pmos\" if row_type.startswith(\"p\") else \"nmos\"\n"
    "        dummy_prefix = \"DUMMYP\" if dummy_type == \"pmos\" else \"DUMMYN\"\n"
    "        row_dev_w    = float(rnodes[0].get(\"geometry\", {}).get(\"width\",  _DUMMY_PITCH))\n"
    "        row_dev_h    = float(rnodes[0].get(\"geometry\", {}).get(\"height\", 0.5))\n"
    "\n"
    "        n_active        = len(rnodes)\n"
    "        n_total_dummies = n_slots - n_active\n"
    "\n"
    "        if n_total_dummies <= 0:\n"
    "            continue  # row already full width\n"
    "\n"
    "        n_left  = n_total_dummies // 2        # floor -> left\n"
    "        n_right = n_total_dummies - n_left    # ceil  -> right\n"
    "\n"
    "        # Shift real transistors right to make room for left dummies\n"
    "        x_offset = n_left * _DUMMY_PITCH\n"
    "        for n in rnodes:\n"
    "            n[\"geometry\"][\"x\"] = round(float(n[\"geometry\"][\"x\"]) + x_offset, 6)\n"
    "\n"
    "        # Left dummies: slots 0 .. n_left-1\n"
    "        for i in range(n_left):\n"
    "            dummy_counter += 1\n"
    "            new_dummies.append({\n"
    "                \"id\": f\"{dummy_prefix}_L_{dummy_counter}\",\n"
    "                \"type\": dummy_type,\n"
    "                \"is_dummy\": True,\n"
    "                \"geometry\": {\n"
    "                    \"x\": round(i * _DUMMY_PITCH, 6),\n"
    "                    \"y\": ry,\n"
    "                    \"width\":  row_dev_w,\n"
    "                    \"height\": row_dev_h,\n"
    "                    \"orientation\": \"R0\",\n"
    "                },\n"
    "                \"electrical\": {\"nf\": 1},\n"
    "                \"abutment\": {\"abut_left\": False, \"abut_right\": False},\n"
    "            })\n"
    "\n"
    "        # Right dummies: slots (n_left + n_active) .. n_slots-1\n"
    "        right_start = n_left + n_active\n"
    "        for i in range(n_right):\n"
    "            dummy_counter += 1\n"
    "            new_dummies.append({\n"
    "                \"id\": f\"{dummy_prefix}_R_{dummy_counter}\",\n"
    "                \"type\": dummy_type,\n"
    "                \"is_dummy\": True,\n"
    "                \"geometry\": {\n"
    "                    \"x\": round((right_start + i) * _DUMMY_PITCH, 6),\n"
    "                    \"y\": ry,\n"
    "                    \"width\":  row_dev_w,\n"
    "                    \"height\": row_dev_h,\n"
    "                    \"orientation\": \"R0\",\n"
    "                },\n"
    "                \"electrical\": {\"nf\": 1},\n"
    "                \"abutment\": {\"abut_left\": False, \"abut_right\": False},\n"
    "            })\n"
    "\n"
    "        print(f\"[LAYOUT]  y={ry:>7.3f}: {n_active} active | \"\n"
    "              f\"{n_left}L + {n_right}R dummies | total={n_slots}\", flush=True)\n"
    "\n"
    "    if dummy_counter > 0:\n"
    "        print(f\"[LAYOUT]  Done: {dummy_counter} dummies, \"\n"
    "              f\"all rows = {global_max_right:.3f}um ({n_slots} slots)\", flush=True)\n"
    "    else:\n"
    "        print(\"[LAYOUT]  All rows already full width\", flush=True)\n"
    "\n"
    "    return active_nodes + new_dummies\n"
    "\n"
    "\n"
)

new_text = text[:start_idx] + new_block + text[end_idx:]
path.write_text(new_text, encoding="utf-8")

# Verify syntax
try:
    ast.parse(new_text)
    open("tests/_patch_result.txt", "w").write("OK")
except SyntaxError as e:
    open("tests/_patch_result.txt", "w").write(f"ERROR: {e}")
