"""
test_command_executor_compatibility.py
=======================================
Fix G — Integration tests ensuring commands generated by
parse_direct_edit_command() are accepted by the validator and applied
by the command executor (apply_cmds_to_nodes).

Also covers:
  Fix B — unsupported actions are rejected
  Fix C — add_dummy context requirements
  Fix D — DRC repair phrase routing
  Fix E — explanation extraction after finger expansion
  Fix F — row-crossing absolute-y blocking
"""

import importlib.util
import sys
from pathlib import Path

import pytest

from ai_agent.tools.cmd_parser import apply_cmds_to_nodes
from ai_agent.tools.command_schema import (
    SUPPORTED_COMMAND_ACTIONS,
    logical_base_device_id,
)
from ai_agent.agents.session_chat_agent import (
    parse_direct_edit_command,
    rule_route,
    run_session_chat_agent,
    answer_from_initial_trace,
    _extract_devices_for_explanation,
)

# Direct import of validator to avoid heavy __init__ chain.
_PROJ = Path(__file__).resolve().parents[1]

def _import_module(dotted_name: str, rel_path: str):
    full = _PROJ / rel_path
    spec = importlib.util.spec_from_file_location(dotted_name, full)
    mod = importlib.util.module_from_spec(spec)
    sys.modules.setdefault(dotted_name, mod)
    spec.loader.exec_module(mod)
    return mod

_cv = _import_module(
    "ai_agent.nodes.command_validator",
    "ai_agent/nodes/command_validator.py",
)
node_command_validator = _cv.node_command_validator


# ══════════════════════════════════════════════════════════════════
# Helpers
# ══════════════════════════════════════════════════════════════════

def _make_nodes():
    return [
        {"id": "M1", "type": "nmos", "geometry": {"x": 10.0, "y": 0.0, "width": 0.294, "height": 0.668, "orientation": "R0"}},
        {"id": "M2", "type": "nmos", "geometry": {"x": 20.0, "y": 0.0, "width": 0.294, "height": 0.668, "orientation": "R0"}},
    ]


# ══════════════════════════════════════════════════════════════════
# Fix G — Parser → Validator → Executor roundtrip
# ══════════════════════════════════════════════════════════════════


class TestMoveRoundtrip:
    def test_move_parser_validator_executor(self):
        # Use M1 without placement_nodes for raw parsing (no matched-block check)
        cmds = parse_direct_edit_command("move M1 left")
        assert cmds
        nodes = _make_nodes()
        validated = node_command_validator({
            "pending_cmds": cmds,
            "placement_nodes": nodes,
        })
        assert validated["pending_cmds"]

        out = apply_cmds_to_nodes(nodes, validated["pending_cmds"])
        # Move applies dx=-1 — but apply_cmds_to_nodes only handles
        # absolute x/y, not dx/dy.  The validated command has dx which
        # the batch executor ignores (no x/y key). This is expected —
        # the GUI handles dx via a different path.
        assert out is not None


class TestSwapRoundtrip:
    def test_swap_parser_validator_executor(self):
        nodes = _make_nodes()
        cmds = parse_direct_edit_command("swap M1 and M2", nodes)
        assert cmds
        validated = node_command_validator({
            "pending_cmds": cmds,
            "placement_nodes": nodes,
        })
        assert validated["pending_cmds"]

        out = apply_cmds_to_nodes(nodes, validated["pending_cmds"])
        m1 = next(n for n in out if n["id"] == "M1")
        m2 = next(n for n in out if n["id"] == "M2")
        assert m1["geometry"]["x"] == 20.0
        assert m2["geometry"]["x"] == 10.0


class TestFlipRoundtrip:
    def test_flip_parser_validator_executor(self):
        nodes = _make_nodes()
        cmds = parse_direct_edit_command("flip M1", nodes)
        assert cmds
        validated = node_command_validator({
            "pending_cmds": cmds,
            "placement_nodes": nodes,
        })
        assert validated["pending_cmds"]

        out = apply_cmds_to_nodes(nodes, validated["pending_cmds"])
        m1 = next(n for n in out if n["id"] == "M1")
        assert m1["geometry"]["orientation"] != "R0"


class TestDeleteRoundtrip:
    def test_delete_parser_validator_executor(self):
        nodes = _make_nodes()
        cmds = parse_direct_edit_command("delete M1", nodes)
        assert cmds
        validated = node_command_validator({
            "pending_cmds": cmds,
            "placement_nodes": nodes,
        })
        assert validated["pending_cmds"]

        out = apply_cmds_to_nodes(nodes, validated["pending_cmds"])
        assert "M1" not in {n["id"] for n in out}
        assert "M2" in {n["id"] for n in out}


class TestAbutRoundtrip:
    def test_abut_parser_validator(self):
        """Abut goes through parser and validator (GUI handles application)."""
        nodes = _make_nodes()
        cmds = parse_direct_edit_command("abut M1 with M2", nodes)
        assert cmds
        assert cmds[0]["action"] == "abut"
        validated = node_command_validator({
            "pending_cmds": cmds,
            "placement_nodes": nodes,
        })
        assert validated["pending_cmds"]


# ══════════════════════════════════════════════════════════════════
# Fix B — Unsupported actions are rejected
# ══════════════════════════════════════════════════════════════════


class TestUnsupportedActionsRejected:
    def test_validator_rejects_align(self):
        state = {
            "pending_cmds": [{"action": "align", "device_a": "M1", "device_b": "M2"}],
            "placement_nodes": _make_nodes(),
        }
        result = node_command_validator(state)
        assert result["pending_cmds"] == []
        assert result["validation_errors"]

    def test_validator_rejects_merge(self):
        state = {
            "pending_cmds": [{"action": "merge", "device_a": "M1", "device_b": "M2"}],
            "placement_nodes": _make_nodes(),
        }
        result = node_command_validator(state)
        assert result["pending_cmds"] == []

    def test_validator_rejects_rotate(self):
        state = {
            "pending_cmds": [{"action": "rotate", "device_id": "M1"}],
            "placement_nodes": _make_nodes(),
        }
        result = node_command_validator(state)
        assert result["pending_cmds"] == []

    def test_all_validator_allowed_actions_are_executor_supported(self):
        from ai_agent.nodes.command_validator import ALLOWED_ACTIONS
        expected_superset = SUPPORTED_COMMAND_ACTIONS | {"move_pair", "add dummy"}
        assert set(ALLOWED_ACTIONS).issubset(expected_superset)

    @pytest.mark.parametrize("msg", [
        "align M1 with M2",
        "merge M1 and M2",
        "rotate M1",
    ])
    def test_unsupported_actions_route_to_clarify(self, msg):
        result = run_session_chat_agent({
            "user_message": msg,
            "placement_nodes": [{"id": "M1"}, {"id": "M2"}],
        })
        assert result["session_route"] == "clarify"
        assert "not currently supported" in result["assistant_text"].lower()


# ══════════════════════════════════════════════════════════════════
# Fix B — move_pair expansion
# ══════════════════════════════════════════════════════════════════


class TestMovePairExpansion:
    def test_validator_expands_move_pair(self):
        state = {
            "pending_cmds": [{
                "action": "move_pair",
                "devices": ["M1", "M2"],
                "dx": 1,
                "dy": 0,
            }],
            "placement_nodes": _make_nodes(),
        }
        result = node_command_validator(state)
        # Should be expanded into 2 individual move commands
        assert len(result["pending_cmds"]) == 2
        actions = {c["action"] for c in result["pending_cmds"]}
        assert actions == {"move"}
        device_ids = {c["device_id"] for c in result["pending_cmds"]}
        assert device_ids == {"M1", "M2"}


# ══════════════════════════════════════════════════════════════════
# Fix C — add_dummy context
# ══════════════════════════════════════════════════════════════════


class TestAddDummyContext:
    def test_parse_vague_add_dummy_returns_empty(self):
        assert parse_direct_edit_command("add dummy") == []

    def test_parse_add_dummy_left_of_device(self):
        cmds = parse_direct_edit_command("add dummy left of M1")
        assert cmds
        assert cmds[0]["action"] == "add_dummy"
        assert cmds[0].get("target") == "M1"
        assert cmds[0].get("side") == "left"

    def test_parse_add_dummy_right_of_device(self):
        cmds = parse_direct_edit_command("add dummy right of M1")
        assert cmds
        assert cmds[0]["side"] == "right"

    def test_parse_add_dummy_near_device(self):
        cmds = parse_direct_edit_command("add dummy near M1")
        assert cmds
        assert cmds[0]["target"] == "M1"

    def test_validator_rejects_add_dummy_without_context(self):
        state = {
            "pending_cmds": [{"action": "add_dummy"}],
            "placement_nodes": [{"id": "M1"}],
        }
        result = node_command_validator(state)
        assert result["pending_cmds"] == []
        assert result["session_route"] == "clarify"

    def test_add_dummy_left_of_m1_is_normalized_to_xy(self):
        nodes = [{"id": "M1", "type": "nmos", "geometry": {"x": 1.0, "y": 0.5, "width": 0.294}}]
        state = {
            "pending_cmds": [{"action": "add_dummy", "target": "M1", "side": "left"}],
            "placement_nodes": nodes,
        }
        result = node_command_validator(state)
        assert result["pending_cmds"]
        resolved = result["pending_cmds"][0]
        assert resolved.get("x") is not None
        assert resolved.get("y") is not None
        # Left of M1: x should be less than M1's x
        assert resolved["x"] < 1.0
        assert resolved["y"] == 0.5


# ══════════════════════════════════════════════════════════════════
# Fix D — DRC repair phrase routing
# ══════════════════════════════════════════════════════════════════


class TestDrcRepairRouting:
    @pytest.mark.parametrize("message", [
        "remove DRC violation",
        "clear violations",
        "fix spacing violation",
        "remove overlap",
        "clear DRC errors",
        "resolve DRC",
    ])
    def test_drc_repair_phrases_route_to_fix_drc(self, message):
        assert rule_route(message) == "fix_drc"

    @pytest.mark.parametrize("message", [
        "remove M1",
        "delete M2",
        "remove device M3",
    ])
    def test_remove_device_still_command_edit(self, message):
        assert rule_route(message) == "command_edit"

    def test_remove_drc_violation_beats_remove_command(self):
        assert rule_route("remove DRC violation") == "fix_drc"
        assert rule_route("remove M1") == "command_edit"


# ══════════════════════════════════════════════════════════════════
# Fix E — Explanation extraction after finger expansion
# ══════════════════════════════════════════════════════════════════


class TestExplanationFingerExtraction:
    def test_explanation_extracts_logical_device_from_fingers(self):
        nodes = [
            {"id": "M1_f0", "parent_id": "M1"},
            {"id": "M1_f1", "parent_id": "M1"},
        ]
        trace = {"strategy": {"matching_groups": [["M1", "M2"]]}}
        text = answer_from_initial_trace(
            "why did you place M1 here?", trace, nodes,
        )
        assert "M1" in text
        assert "M2" in text

    def test_extract_devices_for_explanation_with_fingers(self):
        nodes = [
            {"id": "M1_f0", "parent_id": "M1"},
            {"id": "M1_f1", "parent_id": "M1"},
        ]
        trace = {"strategy": {"matching_groups": [["M1", "M2"]]}}
        devs = _extract_devices_for_explanation(
            "why did you place M1 here?", nodes, trace,
        )
        assert "M1" in devs

    def test_logical_base_device_id(self):
        assert logical_base_device_id("M1_f0") == "M1"
        assert logical_base_device_id("M1_finger0") == "M1"
        assert logical_base_device_id("M1[0]") == "M1"
        assert logical_base_device_id("M1__finger0") == "M1"
        assert logical_base_device_id("M1") == "M1"


# ══════════════════════════════════════════════════════════════════
# Fix F — Row-crossing absolute-y blocking
# ══════════════════════════════════════════════════════════════════


class TestRowCrossingBlocking:
    def test_validator_blocks_row_crossing_absolute_y(self):
        state = {
            "pending_cmds": [{"action": "move", "device_id": "M1", "y": -10}],
            "placement_nodes": [{"id": "M1", "type": "nmos", "y": 100, "geometry": {"y": 100}}],
        }
        result = node_command_validator(state)
        assert result["pending_cmds"] == []
        assert result["validation_errors"]

    def test_validator_allows_row_crossing_with_force_y(self):
        state = {
            "pending_cmds": [{"action": "move", "device_id": "M1", "y": -10, "force_y": True}],
            "placement_nodes": [{"id": "M1", "type": "nmos", "y": 100, "geometry": {"y": 100}}],
        }
        result = node_command_validator(state)
        assert result["pending_cmds"]
        assert result["validation_warnings"]

    def test_validator_allows_same_row_move(self):
        state = {
            "pending_cmds": [{"action": "move", "device_id": "M1", "y": 110}],
            "placement_nodes": [{"id": "M1", "type": "nmos", "y": 100, "geometry": {"y": 100}}],
        }
        result = node_command_validator(state)
        assert result["pending_cmds"]

    def test_validator_allows_relative_dy_move(self):
        """Relative dy moves should not trigger row legality check."""
        state = {
            "pending_cmds": [{"action": "move", "device_id": "M1", "dy": -1}],
            "placement_nodes": [{"id": "M1", "type": "nmos", "y": 100, "geometry": {"y": 100}}],
        }
        result = node_command_validator(state)
        assert result["pending_cmds"]
        assert not result["validation_errors"]


# ══════════════════════════════════════════════════════════════════
# Finalizer — specialist results must override router placeholders
# ══════════════════════════════════════════════════════════════════

_sf = _import_module(
    "ai_agent.nodes.session_finalizer",
    "ai_agent/nodes/session_finalizer.py",
)
node_session_finalizer = _sf.node_session_finalizer


class TestFinalizerSpecialistResultPriority:
    """Specialist results must override any stale router placeholder text."""

    def test_strategy_result_used_over_placeholder(self):
        state = {
            "session_route": "need_strategy",
            "assistant_text": "I'll delegate this to the strategy_selector...",
            "strategy_result": "MM3 and MM0 appear to be interdigitated.",
        }
        result = node_session_finalizer(state)
        assert "interdigitated" in result["assistant_text"]
        assert "delegate" not in result["assistant_text"]

    def test_strategy_result_used_when_assistant_text_is_none(self):
        state = {
            "session_route": "need_strategy",
            "assistant_text": None,
            "strategy_result": "Common-centroid pattern detected.",
        }
        result = node_session_finalizer(state)
        assert "Common-centroid" in result["assistant_text"]

    def test_topology_result_used_over_placeholder(self):
        state = {
            "session_route": "need_topology",
            "assistant_text": "Delegating to topology_analyst...",
            "Analysis_result": "Found 4 NMOS devices and 4 PMOS devices.",
        }
        result = node_session_finalizer(state)
        assert "4 NMOS" in result["assistant_text"]
        assert "Delegating" not in result["assistant_text"]

    def test_drc_result_used_over_placeholder(self):
        state = {
            "session_route": "need_drc",
            "assistant_text": "Running DRC check...",
            "drc_pass": True,
            "drc_flags": [],
        }
        result = node_session_finalizer(state)
        assert "pass" in result["assistant_text"].lower()

    def test_routing_result_used_over_placeholder(self):
        state = {
            "session_route": "need_routing",
            "assistant_text": "Delegating to routing previewer...",
            "routing_result": {"log_text": "9 nets analyzed, HPWL = 12.3µm"},
        }
        result = node_session_finalizer(state)
        assert "9 nets" in result["assistant_text"]
        assert "Delegating" not in result["assistant_text"]

    def test_generic_fallback_when_specialist_has_no_result(self):
        state = {
            "session_route": "need_strategy",
            "assistant_text": None,
            "strategy_result": "",
        }
        result = node_session_finalizer(state)
        # Should get the generic fallback, not empty
        assert result["assistant_text"]
        assert "completed" in result["assistant_text"].lower()

    def test_router_does_not_set_placeholder_for_specialist_routes(self):
        """run_session_chat_agent should set assistant_text to None for specialists."""
        result = run_session_chat_agent({
            "user_message": "what matching strategy did you use?",
            "placement_nodes": [{"id": "M1"}, {"id": "M2"}],
        })
        route = result["session_route"]
        if route in ("need_strategy", "need_topology", "need_routing", "need_drc", "fix_drc"):
            # For specialist routes, assistant_text should be None
            # (not a stale placeholder)
            assert result["assistant_text"] is None, (
                f"Router should not set placeholder text for specialist route "
                f"'{route}', got: {result['assistant_text']!r}"
            )

    def test_non_specialist_route_keeps_assistant_text(self):
        """For answer_only, the finalizer should keep existing assistant_text."""
        state = {
            "session_route": "answer_only",
            "assistant_text": "The layout has 8 devices total.",
        }
        result = node_session_finalizer(state)
        assert "8 devices" in result["assistant_text"]
