"""
File Description:
This module synthesizes 2D common-centroid matrix topologies for current mirrors and other ratio-matched analog blocks. It constructs balanced 2D arrays that minimize linear thermal and oxide gradients.

Functions:
- generate_common_centroid_matrix:
    - Role: Generates a 2D common centroid placement matrix for a group of devices.
    - Inputs: 
        - devices (List[Dict]): List of device info dicts, each having 'id' and 'fingers'.
    - Outputs: (Dict) A dictionary containing the matrix, rows, cols, and total fingers.
- format_matrix_for_prompt:
    - Role: Formats the 2D matrix into a human-readable string for the LLM.
    - Inputs: 
        - matrix_data (Dict): The matrix data dictionary generated by generate_common_centroid_matrix.
    - Outputs: (str) A human-readable string representing the 2D matrix.
"""

from typing import List, Dict, Tuple
import math

def generate_common_centroid_matrix(devices: List[Dict]) -> Dict:
    """
    Generate a 2D common centroid placement matrix for a group of devices.

    Algorithm:
    1. Sort devices by finger count (smallest to largest).
    2. The total number of fingers defines the grid size. We aim for a roughly
       square grid (rows approx cols).
    3. We allocate fingers to the grid such that the 'center of mass' for every
       device is exactly at the physical center of the grid.
    4. Smallest devices are placed as close to the center as possible.
    5. Largest devices wrap around the perimeter.

    Parameters
    ----------
    devices : List[Dict]
        List of device info dicts, each must have 'id' and 'fingers'.
        Example: [{"id": "M1", "fingers": 2}, {"id": "M2", "fingers": 4}]

    Returns
    -------
    Dict
        A dictionary containing:
        - "matrix": List[List[str]] representing the 2D assignment of device IDs.
        - "rows": int
        - "cols": int
    """
    if not devices:
        return {"matrix": [], "rows": 0, "cols": 0}

    # Sort devices by finger count (smallest first)
    sorted_devs = sorted(devices, key=lambda d: d.get("fingers", 1))

    total_fingers = sum(d.get("fingers", 1) for d in sorted_devs)
    if total_fingers == 0:
        return {"matrix": [], "rows": 0, "cols": 0}

    # Determine optimal grid dimensions (rows x cols)
    # Standard analog transistors are physically much taller than they are wide (e.g., 2.5:1).
    # To achieve a physically square block, the logical grid must be much wider than it is tall.
    # Furthermore, most analog layouts contain multiple blocks (e.g., PMOS row + NMOS row) stacked vertically.
    # To keep the GLOBAL aspect ratio square, we aggressively favor wider, flatter matrices (target_ratio ~ 5.0).
    
    target_ratio = 5.0
    ideal_cols = math.sqrt(total_fingers * target_ratio)
    
    best_c = total_fingers
    best_r = 1
    best_cost = float('inf')
    
    for r in range(1, total_fingers + 1):
        c = math.ceil(total_fingers / r)
        # Check both the exact ceil and slightly wider grid (to find better symmetric fallbacks)
        for test_c in [c, c + 1]:
            if r * test_c >= total_fingers:
                wasted = (r * test_c) - total_fingers
                aspect_penalty = abs(test_c - ideal_cols)
                # Strictly penalize 1D row placement if we have enough fingers to make a 2D matrix
                oned_penalty = 1000 if (r == 1 and total_fingers >= 4) else 0
                
                # Cost function: prioritize aspect ratio, strongly penalize wasted dummy space and 1D layouts
                cost = aspect_penalty + (wasted * 5.0) + oned_penalty
                
                if cost < best_cost:
                    best_cost = cost
                    best_r = r
                    best_c = test_c

    rows = best_r
    cols = best_c

    matrix = [[None for _ in range(cols)] for _ in range(rows)]

    # To ensure PERFECT common centroid and optimal X/Y symmetry, we must allocate
    # coordinates in symmetric groups (Quads, Pairs, or Singles).
    center_r = (rows - 1) / 2.0
    center_c = (cols - 1) / 2.0

    quads = []
    pairs = []
    singles = []

    used_coords = set()
    for r in range(rows):
        for c in range(cols):
            if (r, c) in used_coords:
                continue

            sym_r = rows - 1 - r
            sym_c = cols - 1 - c

            dist_sq = (r - center_r)**2 + (c - center_c)**2

            pts = list({(r, c), (r, sym_c), (sym_r, c), (sym_r, sym_c)})
            pts.sort()  # Ensure consistent ordering

            if len(pts) == 4:
                quads.append((dist_sq, pts))
            elif len(pts) == 2:
                pairs.append((dist_sq, pts))
            elif len(pts) == 1:
                singles.append((dist_sq, pts))

            for pt in pts:
                used_coords.add(pt)

    # Sort each pool by distance to center
    quads.sort(key=lambda x: (x[0], x[1]))
    pairs.sort(key=lambda x: (x[0], x[1]))
    singles.sort(key=lambda x: (x[0], x[1]))

    # Allocate fingers device by device (smallest to largest)
    for dev in sorted_devs:
        dev_id = dev["id"]
        n = dev.get("fingers", 1)

        while n >= 4 and quads:
            _, pts = quads.pop(0)
            for r, c in pts:
                matrix[r][c] = dev_id
            n -= 4
            
        while n >= 2 and pairs:
            _, pts = pairs.pop(0)
            for r, c in pts:
                matrix[r][c] = dev_id
            n -= 2
            
        # Fallbacks if we need 2 but only have quads
        if n >= 2 and quads:
            # Split a quad into two point-symmetric pairs
            dist_sq, pts = quads.pop(0)
            # pts is sorted, so pts[0]=(r,c) and pts[3]=(sym_r, sym_c) are point-symmetric
            pair1 = [pts[0], pts[3]]
            pair2 = [pts[1], pts[2]]
            for r, c in pair1:
                matrix[r][c] = dev_id
            n -= 2
            # Return the unused pair back to the pool
            pairs.append((dist_sq, pair2))
            pairs.sort(key=lambda x: (x[0], x[1]))

        while n == 1 and singles:
            _, pts = singles.pop(0)
            matrix[pts[0][0]][pts[0][1]] = dev_id
            n -= 1

        if n == 1 and pairs:
            dist_sq, pts = pairs.pop(0)
            matrix[pts[0][0]][pts[0][1]] = dev_id
            n -= 1
            singles.append((dist_sq, [pts[1]]))
            singles.sort(key=lambda x: (x[0], x[1]))
            
        if n == 1 and quads:
            dist_sq, pts = quads.pop(0)
            matrix[pts[0][0]][pts[0][1]] = dev_id
            n -= 1
            # Return remaining 3 as a pair and a single
            pair_rem = [pts[1], pts[2]]
            single_rem = [pts[3]]
            pairs.append((dist_sq, pair_rem))
            pairs.sort(key=lambda x: (x[0], x[1]))
            singles.append((dist_sq, single_rem))
            singles.sort(key=lambda x: (x[0], x[1]))

    # If any empty slots (due to uneven grid or unused fallbacks), fill with "dummy"
    for r in range(rows):
        for c in range(cols):
            if matrix[r][c] is None:
                matrix[r][c] = "dummy"

    # Add mechanical dummy isolation to the extreme left and right of every row
    for r in range(rows):
        matrix[r].insert(0, "dummy")
        matrix[r].append("dummy")
    
    cols += 2

    return {
        "matrix": matrix,
        "rows": rows,
        "cols": cols,
        "total_fingers": total_fingers
    }

def format_matrix_for_prompt(matrix_data: Dict) -> str:
    """Format the 2D matrix into a human-readable string for the LLM."""
    if not matrix_data or not matrix_data.get("matrix"):
        return ""

    matrix = matrix_data["matrix"]
    lines = []
    for r in reversed(range(len(matrix))):  # Top row first
        row_str = " ".join(f"{str(cell):<6}" for cell in matrix[r])
        lines.append(f"    Row {r}: {row_str}")

    return "\n".join(lines)
