# ==============================================================================
# ai_place.tcl - High-Performance Database Integration & Placement Script
# ==============================================================================
# This script parses a layout placement coordinate file generated by the AI
# layout engine and applies it directly to active, memory-resident layout
# views in OpenAccess (OA)-based EDA design environments (e.g. Synopsys
# Custom Compiler or Cadence Virtuoso). It handles device movement, PCell 
# parameter injection (abutment, dimensions), and GUI Property Editor net updates.
# ==============================================================================

# ------------------------------------------------------------------------------
# Core Placement Procedure
# ------------------------------------------------------------------------------
proc ai_place_final {filename target_cell} {
    puts "Starting Layout Radar & Placement... (VERSION 26 - Tap Integration)"
    
    # Get a list of all currently open layout/schematic designs in the EDA session
    set iter [oa::DesignGetOpenDesigns]
    
    # Establish reference to the Native Namespace for standard library/cell/view naming
    set ns [oa::NativeNS]
    
    # Define reference target library names for regular transistors and tap cells
    set libName "SAED_PDK_14" 
    set tapLibName "taps"

    # Attempt to open the placement coordinate file in read-only mode
    if [catch {open $filename r} fp] {
        puts "ERROR: Cannot open $filename"
        return
    }

    # Initialize data structures: hash map for placement data, and list buffers for dummies and taps
    array set ai_data {}
    set dummy_list {} 
    set tap_list {}

    # Read the placement coordinate file line-by-line
    while {[gets $fp line] >= 0} {
        set line [string trim $line]
        if {$line == ""} continue ;# Skip blank lines
        
        # Tokenize the line based on whitespace separators
        set elements [regexp -inline -all -- {\S+} $line]
        set type_flag [lindex $elements 0]
        set is_dummy 0; set cell_type ""
        
        # Branch 1: TAP Cell Injection line (TAP <rail> <cell_type> <x> <y> <orient>)
        if {$type_flag == "TAP"} {
            set rail [lindex $elements 1]
            set cell_type [lindex $elements 2]
            set xPos [lindex $elements 3]
            set yPos [lindex $elements 4]
            set orient [lindex $elements 5]
            # Buffer the tap cell details for instantiation in Phase 3
            lappend tap_list [list $rail $cell_type $xPos $yPos $orient]
            continue ;# Skip remaining transistor parsing blocks for taps
        }
        
        # Branch 2: DUMMY Transistor line (DUMMY <name> <cell_type> <x> <y> <orient> <params...>)
        if {$type_flag == "DUMMY"} {
            set is_dummy 1
            set name [lindex $elements 1]
            set cell_type [lindex $elements 2]
            set xPos [lindex $elements 3]
            set yPos [lindex $elements 4]
            set orient [lindex $elements 5]
            # Add to dummy list for instantiation in Phase 2
            lappend dummy_list $name
            
        # Branch 3: Standard Active Device line (<name> <x> <y> <orient> <params...>)
        } else {
            set name [lindex $elements 0]
            set xPos [lindex $elements 1]
            set yPos [lindex $elements 2]
            set orient [lindex $elements 3]
        }
        
        # Initialize default PCell parameter values and net buffers
        set leftVal ""; set rightVal ""; set l_val ""; set m_val ""; set nf_val ""; set nfin_val ""
        set d_net ""; set g_net ""; set s_net ""; set b_net ""
        
        # Extract PCell parameters using regular expressions
        if {[regexp {left_abut=([01])} $line match val]} { set leftVal $val }
        if {[regexp {right_abut=([01])} $line match val]} { set rightVal $val }
        if {[regexp {l=([0-9.]+)} $line match val]} { set l_val $val }
        if {[regexp {m=([0-9.]+)} $line match val]} { set m_val $val }
        if {[regexp {nf=([0-9.]+)} $line match val]} { set nf_val $val }
        if {[regexp {nfin=([0-9.]+)} $line match val]} { set nfin_val $val }
        
        # Extract terminal nets using regular expressions (format NetName=NetSuffix)
        if {[regexp {D=([^ ]+)} $line match val]} { set d_net $val }
        if {[regexp {G=([^ ]+)} $line match val]} { set g_net $val }
        if {[regexp {S=([^ ]+)} $line match val]} { set s_net $val }
        if {[regexp {B=([^ ]+)} $line match val]} { set b_net $val }
        
        # Store parsed data in the global array indexed by instance name
        set ai_data($name) [list $xPos $yPos $orient $leftVal $rightVal $is_dummy $cell_type $l_val $m_val $nf_val $nfin_val $d_net $g_net $s_net $b_net]
    }
    close $fp ;# Safely close the placement coordinate file

    # Fetch reference handles for active windows and editing contexts to enable visual selection/GUI updates
    set target_win [gi::getActiveWindow]
    if { [catch {gi::getAssistants dePropertyEditor -from $target_win}] } { set target_win [gi::getWindows 2] }
    set target_ctx [de::getActiveContext]
    
    set total_moved 0

    # Iterate through all currently open designs in the EDA session
    while { [set cv [oa::getNext $iter]] != "0" && $cv != "" } {
        set cellStr "UnknownCell"; set viewStr "UnknownView"
        catch { set cellStr [oa::get [oa::getCellName $cv] $ns] }
        catch { set viewStr [oa::get [oa::getViewName $cv] $ns] }

        # Filter: Skip schematic views or designs that do not match our target cell name
        if {$cellStr != $target_cell || [string match -nocase "*schematic*" $viewStr]} { continue }

        puts "-> Targeting Memory: Cell = '$cellStr'"
        
        # Fetch the top hierarchy block of the open cell view design database
        set block [oa::getTopBlock $cv]
        
        # Get an iterator for all layout cell instances currently placed in the design block
        set instIter [oa::getInsts $block]

        # ======================================================================
        # PHASE 1: Move Existing Instances (Active Transistors)
        # ======================================================================
        while { [set inst [oa::getNext $instIter]] != "0" && $inst != "" } {
            set instStr ""
            catch { set instStr [oa::get [oa::getName $inst] $ns] }

            # If the instance has matching target coordinates from our placement file
            if { [info exists ai_data($instStr)] } {
                set target $ai_data($instStr)
                if {[lindex $target 5]} { continue } ;# Skip dummy placement in Phase 1 (dummies are created in Phase 2)

                # Instantly move the instance's origin coordinate in memory
                oa::setOrigin $inst [list [expr {double([lindex $target 0])}] [expr {double([lindex $target 1])}]]
                
                # Instantly update the rotation/mirroring orientation (e.g. R0, MY, R180)
                oa::setOrient $inst [lindex $target 2]
                
                # Inject PCell abutment flags directly into the design database to enable layout diffusion sharing
                set leftVal [lindex $target 3]; set rightVal [lindex $target 4]
                if {$leftVal != ""} { catch {db::setParamValue "leftAbut" -value $leftVal -of $inst} }
                if {$rightVal != ""} { catch {db::setParamValue "rightAbut" -value $rightVal -of $inst} }
                
                incr total_moved
            }
        }

        # ======================================================================
        # PHASE 2: Create Dummies & Size (Instant Database Instantiation)
        # ======================================================================
        foreach dummy_name $dummy_list {
            set target $ai_data($dummy_name)
            set cell_type [lindex $target 6]
            set x [expr {double([lindex $target 0])}]
            set y [expr {double([lindex $target 1])}]
            
            set inst ""
            # Natively create the dummy transistor instance in OpenAccess database memory
            if {[catch {set inst [le::createInst $dummy_name -design $cv -libName $libName -cellName $cell_type -viewName "layout" -origin [list $x $y] -orient [lindex $target 2]]} err]} {
                puts "   ERROR: Could not create $dummy_name."
                continue
            }

            # Set parameters to configure, size, and abut the newly created dummy instance
            set leftVal [lindex $target 3]; set rightVal [lindex $target 4]; set l_val [lindex $target 7]; set m_val [lindex $target 8]; set nf_val [lindex $target 9]; set nfin_val [lindex $target 10]
            
            catch {db::setParamValue "usage" -value "Dummy" -of $inst} ;# Identify instance as a dummy in PDK parameters
            if {$leftVal != ""} { catch {db::setParamValue "leftAbut" -value $leftVal -of $inst} }
            if {$rightVal != ""} { catch {db::setParamValue "rightAbut" -value $rightVal -of $inst} }
            if {$l_val != ""} { catch {db::setParamValue "l" -value $l_val -of $inst} }
            if {$m_val != ""} { catch {db::setParamValue "m" -value $m_val -of $inst} }
            if {$nf_val != ""} { catch {db::setParamValue "nf" -value $nf_val -of $inst} }
            if {$nfin_val != ""} { catch {db::setParamValue "nfin" -value $nfin_val -of $inst} }
            
            puts "   Generated DUMMY $dummy_name ($cell_type)."
        }

        # ======================================================================
        # PHASE 3: Create Taps (Instant Database Instantiation)
        # ======================================================================
        set tap_counter 0
        foreach tap_data $tap_list {
            set rail [lindex $tap_data 0]
            set cell_type [lindex $tap_data 1]
            set x [expr {double([lindex $tap_data 2])}]
            set y [expr {double([lindex $tap_data 3])}]
            set orient [lindex $tap_data 4]
            
            # Generate a unique instance name to avoid collisions
            set name "TAP_${rail}_${tap_counter}"
            incr tap_counter
            
            set inst ""
            # Natively create the Ptap/Ntap cell reference instance in OpenAccess database memory
            if {[catch {set inst [le::createInst $name -design $cv -libName $tapLibName -cellName $cell_type -viewName "layout" -origin [list $x $y] -orient $orient]} err]} {
                puts "   ERROR: Could not create TAP $name. Check if library '$tapLibName' and cell '$cell_type' exist. ($err)"
            } else {
                puts "   Inserted TAP $name ($cell_type) at ($x, $y)."
            }
        }
    }
    
    # ======================================================================
    # PHASE 4: Sequential GUI Property Editor Connectivity Injection
    # ======================================================================
    # Direct database parameter manipulation can sometimes cause UI out-of-sync
    # warnings for complex connectivity parameters. We safely update dummy terminal
    # net configurations sequentially using the GUI's Property Editor assistant.
    puts "-> Applying Properties via Sequential GUI..."
    set propEd ""
    if { [catch {set propEd [gi::getAssistants dePropertyEditor -from $target_win]}] } {
        puts "   >>> WARNING: Open the Property Editor to apply Dummy nets!"
    } else {
        update ;# Process pending GUI event loops
        after 300 ;# Small delay to ensure Property Editor is ready

        foreach dummy_name $dummy_list {
            set target $ai_data($dummy_name)
            set x [expr {double([lindex $target 0])}]
            set y [expr {double([lindex $target 1])}]
            set d_net [lindex $target 11]; set g_net [lindex $target 12]; set s_net [lindex $target 13]; set b_net [lindex $target 14]

            de::deselectAll $target_ctx ;# Clear current layout selection
            set clicked 0
            catch {
                # Visually select the newly created dummy instance by query at its coordinate position
                set fig [de::getActiveFigure $target_win -point [list $x $y] -index 0 -intent none]
                if {$fig != "" && $fig != "0"} { 
                    de::select $fig 
                    set clicked 1
                }
            }
            
            # If selection was successful, programmatically type nets into the GUI Property Editor fields
            if {$clicked} {
                update
                after 250 ;# Wait for Property Editor layout refresh

                if { [catch {
                    # Select the PDK usage property field and configure it as "Dummy"
                    gi::setItemSelection {attributes} -index {usage,all} -in $propEd
                    gi::setCurrentIndex {attributes} -index {usage,Value} -in $propEd
                    gi::setField {attributes} -value {Dummy} -index {usage,Value} -in $propEd
                    
                    # Expand the Terminal Nets section of the Property Editor panel
                    gi::setField {instanceTerminalsExpand} -value {true} -in $propEd
                    
                    # Set the terminal net names for G, D, S, and B respectively
                    if {$g_net != ""} {
                        gi::setCurrentIndex {instanceTerminals} -index {G,Net Name} -in $propEd
                        gi::setField {instanceTerminals} -value $g_net -index {G,Net Name} -in $propEd
                    }
                    if {$d_net != ""} {
                        gi::setCurrentIndex {instanceTerminals} -index {D,Net Name} -in $propEd
                        gi::setField {instanceTerminals} -value $d_net -index {D,Net Name} -in $propEd
                    }
                    if {$s_net != ""} {
                        gi::setCurrentIndex {instanceTerminals} -index {S,Net Name} -in $propEd
                        gi::setField {instanceTerminals} -value $s_net -index {S,Net Name} -in $propEd
                    }
                    if {$b_net != ""} {
                        gi::setCurrentIndex {instanceTerminals} -index {B,Net Name} -in $propEd
                        gi::setField {instanceTerminals} -value $b_net -index {B,Net Name} -in $propEd
                    }
                    
                    # Execute Apply changes to commit updates to design layout database natively
                    gi::executeAction dePropertyEditorApplyChanges -in $propEd
                } err] } {
                    puts "   >>> GUI Error on $dummy_name: $err"
                }
                
                update
                after 150 ;# Cooldown delay to keep the GUI responsive
                
                # RE-APPLY ABUTMENT FLAGS IN CASE GUI CALLBACK RESET THEM
                set leftVal [lindex $target 3]; set rightVal [lindex $target 4]
                if {$leftVal != ""} { catch {db::setParamValue "leftAbut" -value $leftVal -of $fig} }
                if {$rightVal != ""} { catch {db::setParamValue "rightAbut" -value $rightVal -of $fig} }
            }
        }
    }
    
    # Deselect all items to leave a clean visual view for the designer
    de::deselectAll $target_ctx
    puts "--- Complete. Placed: $total_moved | Dummies: [llength $dummy_list] | Taps: [llength $tap_list] ---"
}

# ------------------------------------------------------------------------------
# Alias Procedure wrapper to support simplified 'ai_place' procedure calls
# ------------------------------------------------------------------------------
proc ai_place {filename target_cell} {
    ai_place_final $filename $target_cell
}